version: "3"

volumes:
  mailcatcher-data:
    driver: local
  mysql-database:
    driver: local

  ### ignore folder volume #####
  var:
    driver: local
  vendor:
    driver: local
  node_modules:
    driver: local

services:
  ### ECCube4 ##################################
  ec-cube:
    build:
      context: .
    ports:
      - "${LOCAL_SERVER_PORT}:80"
      # - 4430:443
    volumes:
      ### 同期対象からコストの重いフォルダを除外 #####################
      - "./eccube/var:/var/www/html/var"
      - "./eccube/vendor:/var/www/html/vendor"
      - "./eccube/node_modules:/var/www/html/node_modules"
      - ./eccube:/var/www/html
    environment:
      # EC-CUBE environments
      APP_ENV: "dev"
      APP_DEBUG: 1
      DATABASE_URL: "mysql://root:root@mysql/eccubedb"
      DATABASE_SERVER_VERSION: 5.7
      MAILER_URL: "smtp://mailcatcher:1025"
      ECCUBE_AUTH_MAGIC: "testauthmagic"
    depends_on:
      mysql:
        condition: service_healthy
    container_name: "${PRODUCTION_NAME}_eccube"

  ### Mailcatcher ##################################
  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"
      - "1025:1025"
    container_name: "${PRODUCTION_NAME}_mailcatcher"

  mysql:
    image: mysql:5.7
    # command: --lower_case_table_names=1 # Maybe For Mac OS
    environment:
      MYSQL_ROOT_PASSWORD: root
      # MYSQL_USER: dbuser
      # MYSQL_PASSWORD: secret
    volumes:
      # - ./eccube/mysql-database:/var/lib/mysql
      - ./dockerbuild/grant_to_dbuser.sql:/docker-entrypoint-initdb.d/grant_to_dbuser.sql #飾り
    ports:
      - "${LOCAL_DB_PORT}:3306"
    healthcheck:
      test: mysqladmin ping
      interval: 3s
      timeout: 3s
      retries: 3
    container_name: "${PRODUCTION_NAME}_mysql"

  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   environment:
  #     PMA_HOST: "mysql"
  #     PMA_USER: "root"
  #     PMA_PASSWORD: "root"
  #   depends_on:
  #     - mysql
  #   ports:
  #     - 4444:80
  #   container_name: "${PRODUCTION_NAME}_phpmyadmin"

  ecmove:
    image: sasaken1102s/ecmove:latest
    container_name: "${PRODUCTION_NAME}_ecmove"
    volumes:
      - ./eccube:/var/www/html
      - ./ecmove/root/backup/:/root/backup/
      - ~/.ssh:/root/.ssh
      # - ./ecmove/root/ecmove:/root/ecmove/ #ecmove.shをいじりたいとき
    tty: true
    environment:
      LOCAL_SERVER_PORT: "${LOCAL_SERVER_PORT}"
      STAGING_DIR_PATH: "${STAGING_DIR_PATH}"
      STAGING_DB_NAME: "${STAGING_DB_NAME}"
      STAGING_DB_USER: "${STAGING_DB_USER}"
      STAGING_DB_PASSWORD: "${STAGING_DB_PASSWORD}"
      STAGING_DB_HOST: "${STAGING_DB_HOST}"
      #STAGING_DB_PORT: "${STAGING_DB_PORT}"
      STAGING_SSH_HOST: "${STAGING_SSH_HOST}"
      STAGING_SSH_USER: "${STAGING_SSH_USER}"
      #STAGING_SSH_PORT: "${STAGING_SSH_PORT}
      PRODUCTION_DIR_PATH: "${PRODUCTION_DIR_PATH}"
      PRODUCTION_DB_NAME: "${PRODUCTION_DB_NAME}"
      PRODUCTION_DB_USER: "${PRODUCTION_DB_USER}"
      PRODUCTION_DB_PASSWORD: "${PRODUCTION_DB_PASSWORD}"
      PRODUCTION_DB_HOST: "${PRODUCTION_DB_HOST}"
      PRODUCTION_DB_PORT: "${PRODUCTION_DB_PORT}"
      PRODUCTION_SSH_HOST: "${PRODUCTION_SSH_HOST}"
      PRODUCTION_SSH_USER: "${PRODUCTION_SSH_USER}"
      PRODUCTION_SSH_PORT: "${PRODUCTION_SSH_PORT}"
      ECMOVE_BACKUP_ECCUBE: "${ECMOVE_BACKUP_ECCUBE}"