version: "3"

volumes:
  mailcatcher-data:
    driver: local
  mysql-database:
    driver: local

  ### ignore folder volume #####
  var:
    driver: local
  vendor:
    driver: local
  node_modules:
    driver: local

services:
  ### ECCube4 ##################################
  ec-cube:
    build:
      context: .
    ports:
      - "8800:80"
      # - 4430:443
    volumes:
      ### 同期対象からコストの重いフォルダを除外 #####################
      - "./eccube/var:/var/www/html/var"
      - "./eccube/vendor:/var/www/html/vendor"
      - "./eccube/node_modules:/var/www/html/node_modules"
      - ./eccube:/var/www/html
    environment:
      # EC-CUBE environments
      APP_ENV: "dev"
      APP_DEBUG: 1
      DATABASE_URL: "mysql://root:root@mysql/eccubedb"
      DATABASE_SERVER_VERSION: 5.7
      MAILER_URL: "smtp://mailcatcher:1025"
      ECCUBE_AUTH_MAGIC: "testauthmagic"
    depends_on:
      mysql:
        condition: service_healthy
    container_name: "ecmovetest_eccube"

  ### Mailcatcher ##################################
  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"
      - "1025:1025"
    container_name: "ecmovetest_mailcatcher"

  mysql:
    image: mysql:5.7
    # command: --lower_case_table_names=1 # Maybe For Mac OS
    environment:
      MYSQL_ROOT_PASSWORD: root
      # MYSQL_USER: dbuser
      # MYSQL_PASSWORD: secret
    volumes:
      # - ./eccube/mysql-database:/var/lib/mysql
      - ./dockerbuild/grant_to_dbuser.sql:/docker-entrypoint-initdb.d/grant_to_dbuser.sql #飾り
    ports:
      - "13306:3306"
    healthcheck:
      test: mysqladmin ping
      interval: 3s
      timeout: 3s
      retries: 3
    container_name: "ecmovetest_mysql"

  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   environment:
  #     PMA_HOST: "mysql"
  #     PMA_USER: "root"
  #     PMA_PASSWORD: "root"
  #   depends_on:
  #     - mysql
  #   ports:
  #     - 4444:80
  #   container_name: "ecmovetest_phpmyadmin"

  ecmove:
    image: sasaken1102s/ecmove:latest
    container_name: "ecmovetest_ecmove"
    volumes:
      - ./eccube:/var/www/html
      - ./ecmove/root/backup/:/root/backup/
      - ~/.ssh:/root/.ssh
      # - ./ecmove/root/ecmove:/root/ecmove/ #ecmove.shをいじりたいとき
    tty: true
    environment:
      STAGING_DIR_PATH: "/var/www/html/eccube"
      STAGING_DB_NAME: "eccubedb"
      STAGING_DB_USER: "testuser"
      STAGING_DB_PASSWORD: "123456"
      STAGING_DB_HOST: "localhost"
      #STAGING_DB_PORT: ""
      STAGING_SSH_HOST: "testserver.co.jp"
      STAGING_SSH_USER: "testuser"
      #STAGING_SSH_PORT: "
      PRODUCTION_DIR_PATH: "/var/www/html/eccube"
      PRODUCTION_DB_NAME: "eccubedb"
      PRODUCTION_DB_USER: "testuser"
      PRODUCTION_DB_PASSWORD: "123456"
      PRODUCTION_DB_HOST: "localhost"
      # PRODUCTION_DB_PORT: ""
      PRODUCTION_SSH_HOST: "testserver.co.jp"
      PRODUCTION_SSH_USER: "testuser"
      # PRODUCTION_SSH_PORT: ""
      ECMOVE_BACKUP_ECCUBE: "false"